name: flutterflow_widgets
description: Widget library for FlutterFlow.
version: 0.0.6
homepage: https://github.com/thruthesky/flutterflow_widgets

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
